THREADS: 32
SAMPLE: [
         "WT_CENH3_Rep1_ChIP_SRR4430537",
         "LoCENH3_Rep1_ChIP_SRR4430543",
         "ZmCENH3_Rep1_ChIP_SRR4430549",
         "WT_CENH3_Rep1_input_SRR4430555"
        ]
FEATURES:
      chrName: [
                "Chr1",
                "Chr2",
                "Chr3",
                "Chr4",
                "Chr5"
               ]
      superfamName: [
#                     "All",
#                     "Copia_LTR",
#                     "EnSpm",
                     "Gypsy_LTR"
#                     "Harbinger",
#                     "hAT",
#                     "Helitron",
#                     "LINE1",
#                     "MuDR",
#                     "Pogo_Tc1_Mariner",
#                     "SINE",
#                     "Unclassified",
#                     "Unclassified_DNA",
#                     "Unclassified_LINE",
#                     "Unclassified_LTR"
                    ]
MAPPING:
      mode: "both"
      reference: "data/index/t2t-col.20210610"
COVERAGE:
      regionBodyLength: 2000
      startLabel: "Start"
      endLabel: "End"
      upstream: 2000
      downstream: 2000
      flankName: "2kb"
      binSize: 10
      binName: "10bp"
      sortRegions: "keep"
